version: '3.8'

services:
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  inception:

volumes:
  mariadb_data:
    driver: local